# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            evolved.io
tagline:          "Creative engineers building sophisticated products."
description:      "Evolved is a full service digital agency headquartered in Germany, Dortmund. We transform brands and build businesses."
url:              http://www.evolved.io

authors:
  dennis:
    name:           Dennis Gaidel
    display_name:		Dennis
    gravatar:				
    github:					https://github.com/kickedinthehead
    url:            https://twitter.com/k1ckedinthehead
  sascha:
    name:           Sascha Schwabbauer
    display_name:		Sascha
    gravatar:				
    github:					https://github.com/sascha
    url:            https://twitter.com/_SaschaS
  malte:
    name:           Malte Baumann
    display_name:		Malte
    gravatar:				
    github:					https://github.com/maltebaumann
    url:            https://twitter.com/codingdivision

paginate:         9

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/evolved/evolved.github.io
