# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            EVOLVED
tagline:          "We craft scalable products meeting the demands of your evolving business."
description:      "EVOLVED is a tech company headquartered in Dortmund (Germany) striving to deliver efficient and aesthetic products."
url:              http://www.evolved.io

authors:
  dennis:
    name:           Dennis Gaidel
    display_name:		Dennis
    bio:            "Computer Science student pursuing a Master's degree with emphasis on Machine Learning and Data Mining, software engineer at adesso AG (@adessoAG), photographer and sports addict."
    image:          dennis.jpg
    github:					https://github.com/kickedinthehead
    twitter:        https://twitter.com/k1ckedinthehead
    linkedin:       https://www.linkedin.com/profile/view?id=317772115
  sascha:
    name:           Sascha Schwabbauer
    display_name:		Sascha
    bio:            "computer science student, iOS developer at @9elements, fitness and health enthusiast"
    image:          sascha.jpg
    github:					https://github.com/sascha
    twitter:        https://twitter.com/_SaschaS
    linkedin:       https://www.linkedin.com/profile/view?id=4493681
  malte:
    name:           Malte Baumann
    display_name:		Malte
    bio:            "iOS Developer, Computer Science student"
    image:          malte.jpg
    github:					https://github.com/maltebaumann
    twitter:        https://twitter.com/codingdivision
    linkedin:       https://www.linkedin.com/profile/view?id=238287744

paginate:         6

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/evolved/evolved.github.io
